config/routes.rb
KRF::Application.routes.draw do

  resources :supports

  resources :training_gears

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :sessions
  match 'login' => 'sessions#new'

  resources :users

  resources :authors

  resources :posts do
    resources :comments
  end

  match 'about' => 'pages#about'
  match 'entertainment' => 'pages#entertainment'
  match 'why_opt_in' => 'pages#why_opt_in'

  resources :supports, :only=> [:new, :create]
end

app/models/training_gear.rb
class TrainingGear < ActiveRecord::Base
  attr_accessible :title, :title_picture_id, :details, :description, :status, :category, :published_on, :amazon, :gender, :gear
  set_table_name 'Training_Gear'
  validates :title, presence: true
  validates :description, presence: true

  scope :published, where{{ status.in => ['published']}}
  scope :recent, order("published_on DESC")

  belongs_to :title_picture, class_name: 'Ckeditor::Picture'

  before_save :set_published_on

  def is_published?
  	['published'].include? status
  end

  def set_published_on
  	if is_published? && published_on.nil?
  		self.published_on = Time.zone.now.to_date
  	end
  end
end

app/controllers/training_gears_controller.rb
class TrainingGearsController < InheritedResources::Base
	before_filter :authorize, except: [:index, :show]

	def index
		@current_section = params[:category] || 'Training Gear'

		# for the carousel
		@most_recent = TrainingGear.published.recent.first #.where(category: @current_section)

		# bulid posts query, for current section
		@training_gears = TrainingGear.published.recent #.where(category: @current_section)
		# not including the first one 
		# @training_gears = @training_gears.where( "id != #{@most_recent.id}" ) if @most_recent
		# paginate the posts
		@training_gears = @training_gears.page(params[:page]).per(15)

		respond_to do |format|
			format.html
		end
	end

	def show
		@training_gear = TrainingGear.published.find(params[:id])
		@current_section = "Training Gear" #@training_gear.category

		respond_to do |format|
			format.html
		end
	end

	def new
		@training_gear = TrainingGear.new

		respond_to do |format|
			format.html
		end
	end

	def edit
		@training_gear = TrainingGear.find(params[:id])
	end

	def create
		@training_gear = TrainingGear.new(params[:training_gear])

		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Training Gear Post was successfully created.'}
			else
				format.html { render action: "new" }
			end
		end
	end

	def update
		@training_gear = TrainingGear.find(params[:id])

		respond_to do |format|
			if @training_gear.update_attributes(params[:post])
				format.html { redirect_to @training_gear, notice: 'Training Gear Posts was successfully updated'}
			else
				format.html { render action: "edit"}
			end
		end
	end

	def destroy
		@training_gear = TrainingGear.find(params[:id])
		@training_gear.destroy

		respond_to do |format|
			format.html { redirect_to training_gears_url}
		end
	end
end

app/helpers/training_gears_helper.rb
module TrainingGearsHelper
end

app/views/training_gears/_carousel.html.haml
#carousel.carousel.slide.span9
  .carousel-inner
    .active.item
      - image_file = @most_recent.title_picture ? @most_recent.title_picture.data(:feature) : "filler_feature.jpg"
      = link_to image_tag(image_file), @most_recent
      .carousel-caption.carousel_caption{style:"line-height: 18px; font-size: 11px; color: white;"}
        %h4
          = link_to @most_recent.title, @most_recent

app/views/training_gears/_form.html.haml
= simple_form_for(@training_gear) do |f|
  = f.error_notification

  .form-inputs
  	= f.input :published_on
  	= f.input :title
  	= f.input :details
  	= f.input :description
  	= f.input :status

  .form-actions
    = f.button :submit

app/views/training_gears/edit.html.haml
%h1 Editing training_gear

= render 'form'

= link_to 'Show', @training_gear
\|
= link_to 'Back', training_gears_path

app/views/training_gears/index.html.haml
/ = render partial: 'carousel'

- @training_gears.each do |gear|
  .gear_post_list.span3
    .post_list_thumb_border2.span2
      .post_list_thumb
        = link_to gear do
          = image_tag( gear.title_picture ? gear.title_picture.data(:list) : "filler_list.jpg" )
    .gear_post_list_text.span3
      %p.post_list_gear_post_title
        =link_to gear.title, gear
      / %p.post_list_post_author
      /   Published on
      /   = gear.published_on.strftime("%B %d, %Y")
      / - if gear.details
      /   %p#post_intro_c
      /     =raw gear.details
      .center_button_ig.div
        %a{:href => "http://www.amazon.com" + gear.amazon}
          = image_tag "amazon.gif"

.span9
  %div
    = paginate @training_gears
/ %table
/   %tr
/     %th
/     %th
/     %th

/   - @training_gears.each do |training_gear|
/     %tr
/       %td= link_to 'Show', training_gear
/       %td= link_to 'Edit', edit_training_gear_path(training_gear)
/       %td= link_to 'Destroy', training_gear, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br

/ = link_to 'New Training gear', new_training_gear_path

app/views/training_gears/new.html.haml
%h1 New training_gear
=render 'form'
=link_to 'Back', training_gears_path

app/views/training_gears/show.html.haml
- title @training_gear.title, false
#post_title
  - if @training_gear.title_picture
    = image_tag @training_gear.title_picture.data(:feature)
  %h2= @training_gear.title
#post_author_top.span9
  - if @training_gear.gender.present?
    = @training_gear.gender
    |
  = @training_gear.category
  |
  = @training_gear.gear
.span9  
  .description_b.div.span5
    .g_body=raw @training_gear.description
  .span4=raw @training_gear.details
  .center_button.div
    %a{:href => "http://www.amazon.com" + @training_gear.amazon}
      = image_tag "amazon.gif"

= link_to 'Edit', edit_training_gear_path(@training_gear)
/ \|
/ = link_to 'Back', training_gears_path