config/routes.rb
KRF::Application.routes.draw do

  resources :supports

  resources :training_gears

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :sessions
  match 'login' => 'sessions#new'

  resources :users

  resources :authors

  resources :posts do
    resources :comments
  end

  match 'about' => 'pages#about'
  match 'entertainment' => 'pages#entertainment'
  match 'why_opt_in' => 'pages#why_opt_in'

  resources :supports, :only=> [:new, :create]
end

app/models/author.rb
class Author < ActiveRecord::Base
	attr_accessible :name, :about, :title_picture_id

	validates :name, presence: true

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authorize
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
= simple_form_for(@author) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :about

  .form-actions
    = f.button :submit

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%h1 Listing authors

%table.table.table-bordered.table-striped
  %tr
    %th Name
    %th About
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.name
      %td= author.about
      %td= link_to 'Show', author
      %td= link_to 'Edit', edit_author_path(author)
      %td= link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @author.name
%p
  %b About:
  = @author.about

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path