config/routes.rb
KRF::Application.routes.draw do

  resources :supports

  resources :training_gears

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :sessions
  match 'login' => 'sessions#new'

  resources :users

  resources :authors

  resources :posts do
    resources :comments
  end

  match 'about' => 'pages#about'
  match 'entertainment' => 'pages#entertainment'
  match 'why_opt_in' => 'pages#why_opt_in'

  resources :supports, :only=> [:new, :create]
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :title_picture_id, :intro, :body, :status, :author_id, :category, :published_on, :views

	validates :title, presence: true
	validates :intro, presence: true
	validates :body, presence: true

	belongs_to :author
  has_many :comments

	scope :published, where{{ status.in => ['published', 'p_featured', 'f_training', 'f_nutrition', 'f_review'] }}
  scope :p_featured, where( status: 'p_featured' )
  scope :f_training, where( status: 'f_training')
  scope :f_nutrition, where( status: 'f_nutrition')
  scope :f_review, where( status: 'f_review')
  scope :recent, order("published_on DESC")
	
	paginates_per 8
  
  acts_as_taggable_on :tags, :groups
  attr_accessible :tag_list, :group_list

  belongs_to :title_picture, class_name: 'Ckeditor::Picture'

  before_save :set_published_on

  def self.tag_list_for_display_on(name)
    Post.tag_counts_on(name).map {|tag| "#{tag.name}(#{tag.count})"}.join(', ')
  end

  def is_published?
    ['published', 'p_featured', 'f_training', 'f_nutrition', 'f_review'].include? status
  end

  def tags_count
    tags_on(:tags).count
  end

  def groups_count
    tags_on(:groups).count
  end

  def related_posts
    @related_posts ||= begin
      related = find_related_groups
      related = related.select {|post| post.is_published? }
      related[0..2]
    end
  end

  # before_save
  def set_published_on
    if is_published? && published_on.nil?
      self.published_on = Time.zone.now.to_date
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @current_section = params[:category] || ''

    # for the carousel
    @most_recent = Post.published.where(category: @current_section).recent.first

    # bulid posts query, for current section
    @posts = Post.published.where(category: @current_section).recent
    # not including the first one 
    @posts = @posts.where( "id != #{@most_recent.id}" ) if @most_recent # and (@current_section == 'traininggear')
    # paginate the posts
    @posts = @posts.page(params[:page]).per(9)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.published.find(params[:id])
    @post.increment!(:views) unless current_user
    @current_section = @post.category
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_carousel.html.haml
/ #carousel2.visible-lg{style: "margin-bottom: 15px; width: 100%;"}
/   - image_file = @most_recent.title_picture ? @most_recent.title_picture.data(:feature) : "filler_feature.jpg"
/   = link_to image_tag(image_file), @most_recent
/   .container
/     .carousel_caption{style:"line-height: 18px; font-size: 11px; color: white;"}
/       %h4
/         = link_to @most_recent.title, @most_recent
/       %p#post_intro_c
/         = raw @most_recent.intro

#carousel.carousel.slide.hidden-xs{"data-ride" => "carousel", style: "margin-left: 15px; margin-right: 15px; margin-bottom: 15px;"}
  .carousel-inner
    .item.active
      - if post = @most_recent # Post.published.recent.first
        - if post.title_picture
          = link_to post do
            = image_tag post.title_picture.data(:front)
        - else
          = link_to post do
            = image_tag ("filler_front.jpg")
        .carousel-caption.carousel_caption.hidden-xs
          %h5=link_to post.title, post
        .carousel-caption.carousel_caption_small.visible-xs
          %h5=link_to post.title, post

#carousel.carousel.slide.visible-xs{"data-ride" => "carousel", style: "margin-left: 15px; margin-right: 15px; margin-bottom: 15px;"}
  .carousel-inner
    .item.active
      - if post = @most_recent # Post.published.recent.first
        - if post.title_picture
          = link_to post do
            = image_tag post.title_picture.data(:front)
        - else
          = link_to post do
            = image_tag ("filler_front.jpg")
        .carousel-caption.carousel_caption.hidden-xs
          %h5=link_to post.title, post
        .carousel-caption.carousel_caption_small.visible-xs
          %h5=link_to post.title, post

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
  	= f.input :published_on
    = f.input :title
    = f.input :intro
    = f.input :body
    = f.input :status
    = f.association :author
    
  .form-actions
    = f.button :submit

app/views/posts/_gear_post.html.haml
.gear_post_list.span3
  .post_list_thumb_border2.span2
    .post_list_thumb
      = link_to post do
        = image_tag( post.title_picture ? post.title_picture.data(:list) : "filler_list.jpg" )
  .gear_post_list_text.span3
    %p.post_list_gear_post_title
      =link_to post.title, post
    %p.post_list_post_author
      Published on
      = post.published_on.strftime("%B %d, %Y")
    - if post.intro
      %p#post_intro_c
        =raw post.intro

app/views/posts/_post.html.haml
.post_list.row.visible-lg.visible-md{style: "margin-left: 15px; max-width: 677px;"}
  .post_list_thumb_border.col-lg-3.col-md-4{style: "padding-left: 0; padding-right: 0;"}
    .post_list_thumb
      - if post.title_picture
        = link_to post do
          = image_tag post.title_picture.data(:list), {style: "width: 100%"}
      - else
        = link_to post do
          = image_tag "filler_list.jpg", {style: "width: 100%"}
  .post_list_text.col-lg-8.col-md-7{style: "padding-left: 0; padding-right: 0;"}
    %p.post_list_post_title
      =link_to post.title, post
    %p.post_list_post_author
      Written by
      = post.author.name
      |
      = post.category
      | Published on
      = post.published_on.strftime("%B %d, %Y")
    .front_into{style: "font-size: 12px; font-weight: bold;"}=raw post.intro
    %br.visible-md
.row.visible-xs{style: "margin-left: 15px;"}
  .small_front_list_title
    .cat_promo_title=link_to post.title, post
  .small_front_image
    - if post.title_picture
      = link_to post do
        = image_tag post.title_picture.data(:flist)
    - else
      = link_to post do
        = image_tag ("front3.jpg"), {style: "width: 95%"}
.row.visible-sm{style: "margin-left: 15px;"}
  .small_front_list_title
    .cat_promo_title=link_to post.title, post
  .small_front_image
    - if post.title_picture
      = link_to post do
        = image_tag post.title_picture.data(:flist)
    - else
      = link_to post do
        = image_tag ("front3.jpg"), {style: "width: 95%"}

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
/ = render partial: 'carousel'

- @posts.each do |post|
  - partial_file = @current_section == 'traininggear' ? 'gear_post' : 'post'
  = render partial: partial_file, locals: { post: post }

.col-xs-12
  %div
    = paginate @posts

app/views/posts/index.old.html.haml
/ %h3#post_list_section_title
/   = @current_section.titleize
- if
  - @current_section == 'traininggear'
  - @most_recent = Post.published.where(category: @current_section).order("published_on DESC")
  - @most_recent[0..0].each do |post|
    #carousel.carousel.slide.span9
      .carousel-inner
        .active.item
          - if post.title_picture
            = link_to post do 
              = image_tag post.title_picture.data(:feature)
          - else
            = link_to post do 
              = image_tag ("filler_feature.jpg")
          .carousel-caption{style:"line-height: 18px; font-size: 11px; color: white;"}
            %h4
              =link_to post.title, post
            %p#post_intro_c
              =raw post.intro
  - @most_recent[0..-1].each do |post|
    %div.gear_post_list.span3
      %div.post_list_thumb_border2.span2
        %div.post_list_thumb
          - if post.title_picture
            = link_to post do
              = image_tag post.title_picture.data(:list)
          - else
            = link_to post do
              = image_tag ("filler_list.jpg")
      %div.gear_post_list_text.span3
        %p.post_list_gear_post_title
          =link_to post.title, post
        %p.post_list_post_author
          Published on
          = post.published_on.strftime("%B %d, %Y")
        - if post.intro
          %p#post_intro_c
            =raw post.intro
- else
  - @most_recent = Post.published.where(category: @current_section).order("published_on DESC")
  - @most_recent[0..0].each do |post|
    #carousel.carousel.slide.span9
      .carousel-inner
        .active.item
          - if post.title_picture
            = link_to post do 
              = image_tag post.title_picture.data(:feature)
          - else
            = link_to post do 
              = image_tag ("filler_feature.jpg")
          .carousel-caption{style:"line-height: 18px; font-size: 11px; color: white;"}
            %h4
              =link_to post.title, post
            %p#post_intro_c
              =raw post.intro

  - @most_recent[1..-1].each do |post|
    %div.post_list.span9
      %div.post_list_thumb_border.span2
        %div.post_list_thumb
          - if post.title_picture
            = link_to post do
              = image_tag post.title_picture.data(:list)
          - else
            = link_to post do
              = image_tag "filler_list.jpg"
      %div.post_list_text.span6
        %p.post_list_post_title
          =link_to post.title, post
        %p.post_list_post_author
          Written by
          = post.author.name
          | Published on
          = post.published_on.strftime("%B %d, %Y")
        %p.post_intro_one
          =raw post.intro
  .span9
    %div
      = paginate @posts

/ - if @posts.empty?
/   %p You're too early! Please check back soon for new articles to be posted.
/ - else  
/   - @most_recent = Post.published.where(category: @current_section == 'traininggear').order("published_on DESC")
/   - @most_recent[0..0].each do |post|
/     %div.span3
/       %div.post_list_thumb_border.span2
/         %div.post_list_thumb
/           - if post.title_picture
/             = link_to post do
/               = image_tag post.title_picture.data(:list)
/           - else
/             = link_to post do
/               = image_tag "filler_list.jag"
/       %div.post_list_text.span3
/         %p.post_list_post_title
/           =link_to post.title, post
/         %p.post_list_post_author
/           Written by
/           = post.author.name
/           | Published on
/           = post.published_on.strftime("%B %d, %Y")

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
- title @post.title, false
#post_title
  %h2= @post.title
#post_author_top.span9
  Written by
  = @post.author.name
  | Published on
  = @post.published_on.strftime("%B %d, %Y")
%br
%br
.post_intro_p=raw @post.intro
.post_body=raw @post.body
#post_author_bottom
  %h4{style:"color: #600; margin: 10px"}= @post.author.name
  #author_about
    = @post.author.about
.hidden-xs.hidden-sm
  - if @post.related_posts.present?
    #post_related.col-lg-9.col-md-9
      %h4{style:"margin-bottom: 5px; margin-left: 10px; margin-top: 10px"} Related Posts
      - @post.related_posts.each do |rpost|
        .related.col-lg-4.col-md-4
          - if rpost.title_picture
            = link_to rpost do
              = image_tag rpost.title_picture.data(:list)
          - else
            = link_to rpost do
              = image_tag "filler_list.jpg"
          %div.related_title
            = link_to truncate(rpost.title, :length => 25), rpost
          %div.related_intro
            =raw truncate(rpost.intro, :length => 100)
%br
- if current_user
  = link_to 'Edit', edit_admin_post_path(@post)

/ #comments
/   %h2 Comments
/   = render @post.comments
/   = render "comments/new"