config/routes.rb
KRF::Application.routes.draw do

  resources :supports

  resources :training_gears

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :sessions
  match 'login' => 'sessions#new'

  resources :users

  resources :authors

  resources :posts do
    resources :comments
  end

  match 'about' => 'pages#about'
  match 'entertainment' => 'pages#entertainment'
  match 'why_opt_in' => 'pages#why_opt_in'

  resources :supports, :only=> [:new, :create]
end

app/views/layouts/_ad_180x150.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Meticufit - Sidbar - Small -->
<ins class="adsbygoogle"
     style="display:inline-block;width:180px;height:150px"
     data-ad-client="ca-pub-7153698131568804"
     data-ad-slot="3518406268"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/layouts/_ad_200x200.html.erb
<center><script type="text/javascript"><!--
google_ad_client = "ca-pub-7153698131568804";
/* KRF Sidebar */
google_ad_slot = "4311411472";
google_ad_width = 200;
google_ad_height = 200;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></center>

app/views/layouts/_ad_300x250.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Meticufit - Sidebar -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-7153698131568804"
     data-ad-slot="5230641861"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/layouts/_ad_300x250_2.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Meticufit - Sidebar2 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-7153698131568804"
     data-ad-slot="9704540662"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  = content_tag :div, :class => "alert alert-#{name == :notice ? 'success' : 'error'}" do
    %a.close{ "data-dismiss" => "alert" }
      %i.icon-remove
    = msg

app/views/layouts/_footer.html.haml
#site_footer
  .container
    .row.visible-lg.visible-md{style: "max-width: 1030px; margin-left: 10px;"}
      .col-lg-4.col-md-4.footer_links.footer_link_hover
        %h3{style: 'color: #fff; line-height: 13px;'} Meticufit
        %hr
        = link_to 'About', '/about'
        %br= link_to 'Subscribe', '/why_opt_in'
        = link_to 'Contact', '/supports/new'
        %br
        %br
        #copyright.logout_link.logout_link_hov
          %br
          Copyright &copy; 2014 Meticufit
          %br
          -if current_user
            Logged in as #{current_user.email} #{link_to 'logout', session_path("current"), method: "delete"}
      .col-lg-4.col-md-4.footer_links.footer_link_hover
        %h3{style: 'color: #fff; line-height: 13px;'} Articles
        %hr
        = link_to 'Training', '/posts?category=training'
        %br= link_to 'Running', '/posts?category=running'
        = link_to 'Nutrition', '/posts?category=nutrition'
        %br= link_to 'Product Reviews', '/posts?category=reviews'
      .col-lg-4.col-md-4.footer_social
        .col-xs-12.footer_social_lower
          / %a{:href => "/", style: 'float: right;'}
          /   = image_tag("nav_pinterest.png", :size => "25x25")
          %a{:href => "https://twitter.com/Meticufit", style: 'float: right; margin-right: 4px;'}
            = image_tag("nav_twitter.png", :size => "25x25")
          %a{:href => "https://www.facebook.com/meticufit", style: 'float: right; margin-right: 4px;'}
            = image_tag("nav_facebook.png", :size => "25x25")
        .col-xs-12
          %a{:href => "/", style: 'float: right; margin-top: 10px;'}
            = image_tag("foot_logo.png")

    .row.visible-xs{style: "margin-left: 10px;"}
      .col-xs-12
        %a{:href => "/", style: 'margin-top: 10px;'}
          = image_tag("foot_logo.png")
      .col-xs-12
        #copyright.logout_link.logout_link_hov
          %br
          Copyright &copy; 2014 Meticufit
          %br
          -if current_user
            Logged in as #{current_user.email} #{link_to 'logout', session_path("current"), method: "delete"}

    .row.visible-sm{style: "margin-left: 10px;"}
      .col-sm-6
        %br
          #copyright.logout_link.logout_link_hov
            Copyright &copy; 2014 Meticufit
            %br
            -if current_user
              Logged in as #{current_user.email} #{link_to 'logout', session_path("current"), method: "delete"}
      .col-sm-6
        %a{:href => "/", style: 'float: right; margin-top: 10px;'}
          = image_tag("foot_logo.png")

  =render 'layouts/amazon_publisher.js'

app/views/layouts/_s_google.html.erb
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

app/views/layouts/_s_twitter.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/_side_mailchimp.html.haml
#side_mail.row
  .span3
    %div#side_mail_banner
      %h4#side_mail_bannertext Get Monthly Updates!
  .span3
    %div
      %p#side_mail_whyopt= link_to 'Why opt-in to our mailing list?', '/why_opt_in'
  %form.form-horizontal{action:"http://elitefitnessedge.us4.list-manage2.com/subscribe?u=ec7250299824e5388c21c7fdb&id=3897a99f2d", method:"post", target:"_blank"}
    %input#side-mailchimp-input{type:"email", name:"EMAIL", placeholder:"Email..."}
    %button#side-mailchimp-button.btn
      %i.icon-envelope
  .span3
    %ul#side_mail_link
      %li New Articles and Posts
      %li New Site Updates
      %li And More!

app/views/layouts/_social.html.haml
.social_bar.center
  #fb-root
  .fb-like{"data-font" => "arial", "data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "false", "data-width" => "450"}
  %p
  %a.twitter-share-button{"data-lang" => "en", "data-via" => "twitterapi", :href => "https://twitter.com/share"} Tweet
  %p
  %div.g-plusone{"data-size" => "medium"}
  %p
  %su:badge{:layout => "1"}

app/views/layouts/_social_js.html.erb
<%= render 'layouts/s_facebook' %>
<%= render 'layouts/s_twitter' %>
<%= render 'layouts/s_stumble' %>
<%= render 'layouts/s_google' %>

app/views/layouts/index_layout.html.haml
!!!
%html
  %head
    %title= "Meticufit | #{@current_section && @current_section.titleize} | #{yield :title}"
    /[if lt IE 9]
      %script{"src" => "http://html5shim.googlecode.com/svn/trunk/html5.js", "type" => "text/javascript"}
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    %meta{"name" => "viewport", "content" => "width=device-width, initial-scale=1.0"}
    %meta{:content => "2XzaYUvr0pYsRkt8XSGp4lyvZBTZ_cKOlPvy6fX5L7s", :name => "google-site-verification"}/
    = csrf_meta_tag
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    %script
      = yield :javascripts
      $(function() {
      = yield :javascript_ready
      });
    
    = yield(:head)
  %body{ :id => yield(:body_id)}
    - if @post
      = render 'layouts/social'
    #container.container-fluid{style: "box-shadow: 0px 1px 15px #888;"}
      .row-fluid{style:"margin-left: 0"}
        = render 'layouts/site_navbar'
        / = render 'layouts/blog_navbar'
    .container
      #content.row{style:"margin-left: 0"}
        = render 'layouts/flash', flash: flash
        - if show_title?
          %h1= yield(:title)
        %div.hidden-xs
          = render 'posts/carousel'
          .col-lg-8.col-md-8.col-sm-8.col-xs-12{style: "padding-left: 0;"}= content_for?(:content) ? yield(:content) : yield
          .col-lg-4.col-md-4.col-sm-4.col-xs-12{style: "padding-left: 0;"}
            = render 'layouts/side_bar'
        %div.visible-xs{style: "margin-top: 50px;"}
          = render 'posts/carousel'
          .col-lg-8.col-md-8.col-sm-8.col-xs-12{style: "padding-left: 0; margin-top: 50px;"}= content_for?(:content) ? yield(:content) : yield
          .col-lg-4.col-md-4.col-sm-4.col-xs-12{style: "padding-left: 0;"}
            = render 'layouts/side_bar'

    =render 'layouts/footer'
    - if @post
      =render 'layouts/social_js'

app/views/layouts/show_layout.html.haml
!!!
%html
  %head
    %title= "Meticufit | #{@current_section && @current_section.titleize} | #{yield :title}"
    /[if lt IE 9]
      %script{"src" => "http://html5shim.googlecode.com/svn/trunk/html5.js", "type" => "text/javascript"}
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    %meta{"name" => "viewport", "content" => "width=device-width, initial-scale=1.0"}
    %meta{:content => "2XzaYUvr0pYsRkt8XSGp4lyvZBTZ_cKOlPvy6fX5L7s", :name => "google-site-verification"}/
    = csrf_meta_tag
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    %script
      = yield :javascripts
      $(function() {
      = yield :javascript_ready
      });
    
    = yield(:head)
  %body{ :id => yield(:body_id)}
    - if @post
      = render 'layouts/social'
    #container.container-fluid{style: "box-shadow: 0px 1px 15px #888;"}
      .row-fluid{style:"margin-left: 0"}
        = render 'layouts/site_navbar'
        / = render 'layouts/blog_navbar'
    .container
      #content.row{style:"margin-left: 0"}
        = render 'layouts/flash', flash: flash
        - if show_title?
          %h1= yield(:title)
        %div.hidden-xs
          = render 'layouts/show_title_image'
          .col-lg-8.col-md-8.col-sm-8.col-xs-12= content_for?(:content) ? yield(:content) : yield
          .col-lg-4.col-md-4.col-sm-4.col-xs-12{style: "padding-left: 0;"}
            = render 'layouts/side_bar'
        %div.visible-xs{style: "margin-top: 50px;"}
          = render 'layouts/show_title_image'
          .col-lg-8.col-md-8.col-sm-8.col-xs-12= content_for?(:content) ? yield(:content) : yield
          .col-lg-4.col-md-4.col-sm-4.col-xs-12{style: "padding-left: 0;"}
            = render 'layouts/side_bar'

    =render 'layouts/footer'
    - if @post
      =render 'layouts/social_js'

app/views/layouts/test.html.haml
!!!
%html
  %head
    %title= "Keep Running Free | #{yield :title}"
    /[if lt IE 9]
      %script{"src" => "http://html5shim.googlecode.com/svn/trunk/html5.js", "type" => "text/javascript"}
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    %meta{"name" => "viewport", "content" => "width=device-width, initial-scale=1.0"}
    = csrf_meta_tag
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    %script
      = yield :javascripts
      $(function() {
      = yield :javascript_ready
      });
    
    = yield(:head)
  %body{ :id => yield(:body_id)}
    %div
      #container.container-fluid
        .row-fluid{style:"margin-left: 0"}
          #site_navbar
            .navbar
              .navbar-inner
                .container
                  %a.brand{:href => "/"}
                    = image_tag("header_logo_black.png", size:"226x39")
        =# render 'layouts/site_navbar'
        / = render 'layouts/blog_navbar'
    .container
      #content.row{style:"margin-left: 0"}
        = render 'layouts/flash', flash: flash
        - if show_title?
          %h1= yield(:title)
        .span9= content_for?(:content) ? yield(:content) : yield
        .span3.offset9{style:"margin-left: 40px"}
          =# render 'layouts/side_bar'
      -#.row{style:"margin-left: 0"}
      -#  = render 'layouts/footer'
    =render 'layouts/footer'